// Generated by gencpp from file atom_msgs/DeleteCollection.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_DELETECOLLECTION_H
#define ATOM_MSGS_MESSAGE_DELETECOLLECTION_H

#include <ros/service_traits.h>


#include <atom_msgs/DeleteCollectionRequest.h>
#include <atom_msgs/DeleteCollectionResponse.h>


namespace atom_msgs
{

struct DeleteCollection
{

typedef DeleteCollectionRequest Request;
typedef DeleteCollectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteCollection
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::DeleteCollection > {
  static const char* value()
  {
    return "7153cde40c335857eb1dbcb61409e936";
  }

  static const char* value(const ::atom_msgs::DeleteCollection&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::DeleteCollection > {
  static const char* value()
  {
    return "atom_msgs/DeleteCollection";
  }

  static const char* value(const ::atom_msgs::DeleteCollection&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::DeleteCollectionRequest> should match
// service_traits::MD5Sum< ::atom_msgs::DeleteCollection >
template<>
struct MD5Sum< ::atom_msgs::DeleteCollectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::DeleteCollection >::value();
  }
  static const char* value(const ::atom_msgs::DeleteCollectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::DeleteCollectionRequest> should match
// service_traits::DataType< ::atom_msgs::DeleteCollection >
template<>
struct DataType< ::atom_msgs::DeleteCollectionRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::DeleteCollection >::value();
  }
  static const char* value(const ::atom_msgs::DeleteCollectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::DeleteCollectionResponse> should match
// service_traits::MD5Sum< ::atom_msgs::DeleteCollection >
template<>
struct MD5Sum< ::atom_msgs::DeleteCollectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::DeleteCollection >::value();
  }
  static const char* value(const ::atom_msgs::DeleteCollectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::DeleteCollectionResponse> should match
// service_traits::DataType< ::atom_msgs::DeleteCollection >
template<>
struct DataType< ::atom_msgs::DeleteCollectionResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::DeleteCollection >::value();
  }
  static const char* value(const ::atom_msgs::DeleteCollectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_DELETECOLLECTION_H
