// Generated by gencpp from file atom_msgs/DeleteCollectionRequest.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_DELETECOLLECTIONREQUEST_H
#define ATOM_MSGS_MESSAGE_DELETECOLLECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atom_msgs
{
template <class ContainerAllocator>
struct DeleteCollectionRequest_
{
  typedef DeleteCollectionRequest_<ContainerAllocator> Type;

  DeleteCollectionRequest_()
    : collection_name()  {
    }
  DeleteCollectionRequest_(const ContainerAllocator& _alloc)
    : collection_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _collection_name_type;
  _collection_name_type collection_name;





  typedef boost::shared_ptr< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteCollectionRequest_

typedef ::atom_msgs::DeleteCollectionRequest_<std::allocator<void> > DeleteCollectionRequest;

typedef boost::shared_ptr< ::atom_msgs::DeleteCollectionRequest > DeleteCollectionRequestPtr;
typedef boost::shared_ptr< ::atom_msgs::DeleteCollectionRequest const> DeleteCollectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator1> & lhs, const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.collection_name == rhs.collection_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator1> & lhs, const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6315d1939d029d965ff7b2db030e5c5";
  }

  static const char* value(const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6315d1939d029d9ULL;
  static const uint64_t static_value2 = 0x65ff7b2db030e5c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/DeleteCollectionRequest";
  }

  static const char* value(const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string collection_name\n"
;
  }

  static const char* value(const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collection_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteCollectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_msgs::DeleteCollectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "collection_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.collection_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_DELETECOLLECTIONREQUEST_H
