// Generated by gencpp from file atom_msgs/DepthLabels.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_DEPTHLABELS_H
#define ATOM_MSGS_MESSAGE_DEPTHLABELS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atom_msgs
{
template <class ContainerAllocator>
struct DepthLabels_
{
  typedef DepthLabels_<ContainerAllocator> Type;

  DepthLabels_()
    : pattern_name()
    , detected(false)
    , idxs()
    , idxs_limit_points()  {
    }
  DepthLabels_(const ContainerAllocator& _alloc)
    : pattern_name(_alloc)
    , detected(false)
    , idxs(_alloc)
    , idxs_limit_points(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pattern_name_type;
  _pattern_name_type pattern_name;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _idxs_type;
  _idxs_type idxs;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _idxs_limit_points_type;
  _idxs_limit_points_type idxs_limit_points;





  typedef boost::shared_ptr< ::atom_msgs::DepthLabels_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::DepthLabels_<ContainerAllocator> const> ConstPtr;

}; // struct DepthLabels_

typedef ::atom_msgs::DepthLabels_<std::allocator<void> > DepthLabels;

typedef boost::shared_ptr< ::atom_msgs::DepthLabels > DepthLabelsPtr;
typedef boost::shared_ptr< ::atom_msgs::DepthLabels const> DepthLabelsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::DepthLabels_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::DepthLabels_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atom_msgs::DepthLabels_<ContainerAllocator1> & lhs, const ::atom_msgs::DepthLabels_<ContainerAllocator2> & rhs)
{
  return lhs.pattern_name == rhs.pattern_name &&
    lhs.detected == rhs.detected &&
    lhs.idxs == rhs.idxs &&
    lhs.idxs_limit_points == rhs.idxs_limit_points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atom_msgs::DepthLabels_<ContainerAllocator1> & lhs, const ::atom_msgs::DepthLabels_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::DepthLabels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::DepthLabels_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::DepthLabels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::DepthLabels_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::DepthLabels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::DepthLabels_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::DepthLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1feeee9a8d44fc8fa147e3f3e0194a1e";
  }

  static const char* value(const ::atom_msgs::DepthLabels_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1feeee9a8d44fc8fULL;
  static const uint64_t static_value2 = 0xa147e3f3e0194a1eULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::DepthLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/DepthLabels";
  }

  static const char* value(const ::atom_msgs::DepthLabels_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::DepthLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pattern_name\n"
"bool detected\n"
"uint32[] idxs\n"
"uint32[] idxs_limit_points\n"
;
  }

  static const char* value(const ::atom_msgs::DepthLabels_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::DepthLabels_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pattern_name);
      stream.next(m.detected);
      stream.next(m.idxs);
      stream.next(m.idxs_limit_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthLabels_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::DepthLabels_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_msgs::DepthLabels_<ContainerAllocator>& v)
  {
    s << indent << "pattern_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pattern_name);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "idxs[]" << std::endl;
    for (size_t i = 0; i < v.idxs.size(); ++i)
    {
      s << indent << "  idxs[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.idxs[i]);
    }
    s << indent << "idxs_limit_points[]" << std::endl;
    for (size_t i = 0; i < v.idxs_limit_points.size(); ++i)
    {
      s << indent << "  idxs_limit_points[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.idxs_limit_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_DEPTHLABELS_H
