// Generated by gencpp from file atom_msgs/Detection2D.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_DETECTION2D_H
#define ATOM_MSGS_MESSAGE_DETECTION2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atom_msgs
{
template <class ContainerAllocator>
struct Detection2D_
{
  typedef Detection2D_<ContainerAllocator> Type;

  Detection2D_()
    : x(0.0)
    , y(0.0)
    , id(0)  {
    }
  Detection2D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::atom_msgs::Detection2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::Detection2D_<ContainerAllocator> const> ConstPtr;

}; // struct Detection2D_

typedef ::atom_msgs::Detection2D_<std::allocator<void> > Detection2D;

typedef boost::shared_ptr< ::atom_msgs::Detection2D > Detection2DPtr;
typedef boost::shared_ptr< ::atom_msgs::Detection2D const> Detection2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::Detection2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::Detection2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atom_msgs::Detection2D_<ContainerAllocator1> & lhs, const ::atom_msgs::Detection2D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atom_msgs::Detection2D_<ContainerAllocator1> & lhs, const ::atom_msgs::Detection2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::Detection2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::Detection2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::Detection2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::Detection2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::Detection2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::Detection2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::Detection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7de5b7b91916c5429af17aa0dec8ef0f";
  }

  static const char* value(const ::atom_msgs::Detection2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7de5b7b91916c542ULL;
  static const uint64_t static_value2 = 0x9af17aa0dec8ef0fULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::Detection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/Detection2D";
  }

  static const char* value(const ::atom_msgs::Detection2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::Detection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"uint32 id\n"
"\n"
;
  }

  static const char* value(const ::atom_msgs::Detection2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::Detection2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::Detection2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_msgs::Detection2D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_DETECTION2D_H
