// Generated by gencpp from file atom_msgs/GetAdditionalTfsInteractiveMarker.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_GETADDITIONALTFSINTERACTIVEMARKER_H
#define ATOM_MSGS_MESSAGE_GETADDITIONALTFSINTERACTIVEMARKER_H

#include <ros/service_traits.h>


#include <atom_msgs/GetAdditionalTfsInteractiveMarkerRequest.h>
#include <atom_msgs/GetAdditionalTfsInteractiveMarkerResponse.h>


namespace atom_msgs
{

struct GetAdditionalTfsInteractiveMarker
{

typedef GetAdditionalTfsInteractiveMarkerRequest Request;
typedef GetAdditionalTfsInteractiveMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAdditionalTfsInteractiveMarker
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarker > {
  static const char* value()
  {
    return "a13bc23ac434a77acb1a1c56a01ae850";
  }

  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarker&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarker > {
  static const char* value()
  {
    return "atom_msgs/GetAdditionalTfsInteractiveMarker";
  }

  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarker&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest> should match
// service_traits::MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest> should match
// service_traits::DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarker >
template<>
struct DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse> should match
// service_traits::MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse> should match
// service_traits::DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarker >
template<>
struct DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetAdditionalTfsInteractiveMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_GETADDITIONALTFSINTERACTIVEMARKER_H
