// Generated by gencpp from file atom_msgs/GetDataset.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_GETDATASET_H
#define ATOM_MSGS_MESSAGE_GETDATASET_H

#include <ros/service_traits.h>


#include <atom_msgs/GetDatasetRequest.h>
#include <atom_msgs/GetDatasetResponse.h>


namespace atom_msgs
{

struct GetDataset
{

typedef GetDatasetRequest Request;
typedef GetDatasetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDataset
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::GetDataset > {
  static const char* value()
  {
    return "f95a59a2834b82b7b9f74a87d123f078";
  }

  static const char* value(const ::atom_msgs::GetDataset&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::GetDataset > {
  static const char* value()
  {
    return "atom_msgs/GetDataset";
  }

  static const char* value(const ::atom_msgs::GetDataset&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::GetDatasetRequest> should match
// service_traits::MD5Sum< ::atom_msgs::GetDataset >
template<>
struct MD5Sum< ::atom_msgs::GetDatasetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetDataset >::value();
  }
  static const char* value(const ::atom_msgs::GetDatasetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetDatasetRequest> should match
// service_traits::DataType< ::atom_msgs::GetDataset >
template<>
struct DataType< ::atom_msgs::GetDatasetRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetDataset >::value();
  }
  static const char* value(const ::atom_msgs::GetDatasetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::GetDatasetResponse> should match
// service_traits::MD5Sum< ::atom_msgs::GetDataset >
template<>
struct MD5Sum< ::atom_msgs::GetDatasetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetDataset >::value();
  }
  static const char* value(const ::atom_msgs::GetDatasetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetDatasetResponse> should match
// service_traits::DataType< ::atom_msgs::GetDataset >
template<>
struct DataType< ::atom_msgs::GetDatasetResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetDataset >::value();
  }
  static const char* value(const ::atom_msgs::GetDatasetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_GETDATASET_H
