// Generated by gencpp from file atom_msgs/GetDatasetResponse.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_GETDATASETRESPONSE_H
#define ATOM_MSGS_MESSAGE_GETDATASETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atom_msgs
{
template <class ContainerAllocator>
struct GetDatasetResponse_
{
  typedef GetDatasetResponse_<ContainerAllocator> Type;

  GetDatasetResponse_()
    : success(false)
    , dataset_json()  {
    }
  GetDatasetResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , dataset_json(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dataset_json_type;
  _dataset_json_type dataset_json;





  typedef boost::shared_ptr< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDatasetResponse_

typedef ::atom_msgs::GetDatasetResponse_<std::allocator<void> > GetDatasetResponse;

typedef boost::shared_ptr< ::atom_msgs::GetDatasetResponse > GetDatasetResponsePtr;
typedef boost::shared_ptr< ::atom_msgs::GetDatasetResponse const> GetDatasetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::GetDatasetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atom_msgs::GetDatasetResponse_<ContainerAllocator1> & lhs, const ::atom_msgs::GetDatasetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.dataset_json == rhs.dataset_json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atom_msgs::GetDatasetResponse_<ContainerAllocator1> & lhs, const ::atom_msgs::GetDatasetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f95a59a2834b82b7b9f74a87d123f078";
  }

  static const char* value(const ::atom_msgs::GetDatasetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf95a59a2834b82b7ULL;
  static const uint64_t static_value2 = 0xb9f74a87d123f078ULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/GetDatasetResponse";
  }

  static const char* value(const ::atom_msgs::GetDatasetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string dataset_json\n"
"\n"
"\n"
;
  }

  static const char* value(const ::atom_msgs::GetDatasetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.dataset_json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDatasetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::GetDatasetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_msgs::GetDatasetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "dataset_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dataset_json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_GETDATASETRESPONSE_H
