// Generated by gencpp from file atom_msgs/GetSensorInteractiveMarker.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_GETSENSORINTERACTIVEMARKER_H
#define ATOM_MSGS_MESSAGE_GETSENSORINTERACTIVEMARKER_H

#include <ros/service_traits.h>


#include <atom_msgs/GetSensorInteractiveMarkerRequest.h>
#include <atom_msgs/GetSensorInteractiveMarkerResponse.h>


namespace atom_msgs
{

struct GetSensorInteractiveMarker
{

typedef GetSensorInteractiveMarkerRequest Request;
typedef GetSensorInteractiveMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensorInteractiveMarker
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::GetSensorInteractiveMarker > {
  static const char* value()
  {
    return "a13bc23ac434a77acb1a1c56a01ae850";
  }

  static const char* value(const ::atom_msgs::GetSensorInteractiveMarker&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::GetSensorInteractiveMarker > {
  static const char* value()
  {
    return "atom_msgs/GetSensorInteractiveMarker";
  }

  static const char* value(const ::atom_msgs::GetSensorInteractiveMarker&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::GetSensorInteractiveMarkerRequest> should match
// service_traits::MD5Sum< ::atom_msgs::GetSensorInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::GetSensorInteractiveMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetSensorInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetSensorInteractiveMarkerRequest> should match
// service_traits::DataType< ::atom_msgs::GetSensorInteractiveMarker >
template<>
struct DataType< ::atom_msgs::GetSensorInteractiveMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetSensorInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::GetSensorInteractiveMarkerResponse> should match
// service_traits::MD5Sum< ::atom_msgs::GetSensorInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::GetSensorInteractiveMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::GetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetSensorInteractiveMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::GetSensorInteractiveMarkerResponse> should match
// service_traits::DataType< ::atom_msgs::GetSensorInteractiveMarker >
template<>
struct DataType< ::atom_msgs::GetSensorInteractiveMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::GetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::GetSensorInteractiveMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_GETSENSORINTERACTIVEMARKER_H
