// Generated by gencpp from file atom_msgs/PointCloudWithLidar3DLabels.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_POINTCLOUDWITHLIDAR3DLABELS_H
#define ATOM_MSGS_MESSAGE_POINTCLOUDWITHLIDAR3DLABELS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include <atom_msgs/Lidar3DLabels.h>

namespace atom_msgs
{
template <class ContainerAllocator>
struct PointCloudWithLidar3DLabels_
{
  typedef PointCloudWithLidar3DLabels_<ContainerAllocator> Type;

  PointCloudWithLidar3DLabels_()
    : header()
    , point_cloud()
    , patterns()  {
    }
  PointCloudWithLidar3DLabels_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point_cloud(_alloc)
    , patterns(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _point_cloud_type;
  _point_cloud_type point_cloud;

   typedef std::vector< ::atom_msgs::Lidar3DLabels_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::atom_msgs::Lidar3DLabels_<ContainerAllocator> >> _patterns_type;
  _patterns_type patterns;





  typedef boost::shared_ptr< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudWithLidar3DLabels_

typedef ::atom_msgs::PointCloudWithLidar3DLabels_<std::allocator<void> > PointCloudWithLidar3DLabels;

typedef boost::shared_ptr< ::atom_msgs::PointCloudWithLidar3DLabels > PointCloudWithLidar3DLabelsPtr;
typedef boost::shared_ptr< ::atom_msgs::PointCloudWithLidar3DLabels const> PointCloudWithLidar3DLabelsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator1> & lhs, const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point_cloud == rhs.point_cloud &&
    lhs.patterns == rhs.patterns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator1> & lhs, const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8718797d8c5c69f369339615842a11b1";
  }

  static const char* value(const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8718797d8c5c69f3ULL;
  static const uint64_t static_value2 = 0x69339615842a11b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/PointCloudWithLidar3DLabels";
  }

  static const char* value(const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/PointCloud2 point_cloud\n"
"Lidar3DLabels[] patterns\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: atom_msgs/Lidar3DLabels\n"
"string pattern_name\n"
"bool detected\n"
"uint32[] idxs\n"
"uint32[] idxs_limit_points\n"
;
  }

  static const char* value(const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point_cloud);
      stream.next(m.patterns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudWithLidar3DLabels_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atom_msgs::PointCloudWithLidar3DLabels_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point_cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.point_cloud);
    s << indent << "patterns[]" << std::endl;
    for (size_t i = 0; i < v.patterns.size(); ++i)
    {
      s << indent << "  patterns[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::atom_msgs::Lidar3DLabels_<ContainerAllocator> >::stream(s, indent + "    ", v.patterns[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_POINTCLOUDWITHLIDAR3DLABELS_H
