// Generated by gencpp from file atom_msgs/SaveCollection.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_SAVECOLLECTION_H
#define ATOM_MSGS_MESSAGE_SAVECOLLECTION_H

#include <ros/service_traits.h>


#include <atom_msgs/SaveCollectionRequest.h>
#include <atom_msgs/SaveCollectionResponse.h>


namespace atom_msgs
{

struct SaveCollection
{

typedef SaveCollectionRequest Request;
typedef SaveCollectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveCollection
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::SaveCollection > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::atom_msgs::SaveCollection&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::SaveCollection > {
  static const char* value()
  {
    return "atom_msgs/SaveCollection";
  }

  static const char* value(const ::atom_msgs::SaveCollection&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::SaveCollectionRequest> should match
// service_traits::MD5Sum< ::atom_msgs::SaveCollection >
template<>
struct MD5Sum< ::atom_msgs::SaveCollectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SaveCollection >::value();
  }
  static const char* value(const ::atom_msgs::SaveCollectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SaveCollectionRequest> should match
// service_traits::DataType< ::atom_msgs::SaveCollection >
template<>
struct DataType< ::atom_msgs::SaveCollectionRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SaveCollection >::value();
  }
  static const char* value(const ::atom_msgs::SaveCollectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::SaveCollectionResponse> should match
// service_traits::MD5Sum< ::atom_msgs::SaveCollection >
template<>
struct MD5Sum< ::atom_msgs::SaveCollectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SaveCollection >::value();
  }
  static const char* value(const ::atom_msgs::SaveCollectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SaveCollectionResponse> should match
// service_traits::DataType< ::atom_msgs::SaveCollection >
template<>
struct DataType< ::atom_msgs::SaveCollectionResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SaveCollection >::value();
  }
  static const char* value(const ::atom_msgs::SaveCollectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_SAVECOLLECTION_H
