// Generated by gencpp from file atom_msgs/SaveCollectionRequest.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_SAVECOLLECTIONREQUEST_H
#define ATOM_MSGS_MESSAGE_SAVECOLLECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace atom_msgs
{
template <class ContainerAllocator>
struct SaveCollectionRequest_
{
  typedef SaveCollectionRequest_<ContainerAllocator> Type;

  SaveCollectionRequest_()
    {
    }
  SaveCollectionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveCollectionRequest_

typedef ::atom_msgs::SaveCollectionRequest_<std::allocator<void> > SaveCollectionRequest;

typedef boost::shared_ptr< ::atom_msgs::SaveCollectionRequest > SaveCollectionRequestPtr;
typedef boost::shared_ptr< ::atom_msgs::SaveCollectionRequest const> SaveCollectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace atom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::atom_msgs::SaveCollectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atom_msgs/SaveCollectionRequest";
  }

  static const char* value(const ::atom_msgs::SaveCollectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::atom_msgs::SaveCollectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveCollectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atom_msgs::SaveCollectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::atom_msgs::SaveCollectionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_SAVECOLLECTIONREQUEST_H
