// Generated by gencpp from file atom_msgs/SetAdditionalTfsInteractiveMarker.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_SETADDITIONALTFSINTERACTIVEMARKER_H
#define ATOM_MSGS_MESSAGE_SETADDITIONALTFSINTERACTIVEMARKER_H

#include <ros/service_traits.h>


#include <atom_msgs/SetAdditionalTfsInteractiveMarkerRequest.h>
#include <atom_msgs/SetAdditionalTfsInteractiveMarkerResponse.h>


namespace atom_msgs
{

struct SetAdditionalTfsInteractiveMarker
{

typedef SetAdditionalTfsInteractiveMarkerRequest Request;
typedef SetAdditionalTfsInteractiveMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAdditionalTfsInteractiveMarker
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarker > {
  static const char* value()
  {
    return "8512eb1fbd109250c8778605b27356c3";
  }

  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarker&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarker > {
  static const char* value()
  {
    return "atom_msgs/SetAdditionalTfsInteractiveMarker";
  }

  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarker&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest> should match
// service_traits::MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest> should match
// service_traits::DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarker >
template<>
struct DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse> should match
// service_traits::MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse> should match
// service_traits::DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarker >
template<>
struct DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SetAdditionalTfsInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetAdditionalTfsInteractiveMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_SETADDITIONALTFSINTERACTIVEMARKER_H
