// Generated by gencpp from file atom_msgs/SetSensorInteractiveMarker.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_SETSENSORINTERACTIVEMARKER_H
#define ATOM_MSGS_MESSAGE_SETSENSORINTERACTIVEMARKER_H

#include <ros/service_traits.h>


#include <atom_msgs/SetSensorInteractiveMarkerRequest.h>
#include <atom_msgs/SetSensorInteractiveMarkerResponse.h>


namespace atom_msgs
{

struct SetSensorInteractiveMarker
{

typedef SetSensorInteractiveMarkerRequest Request;
typedef SetSensorInteractiveMarkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensorInteractiveMarker
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::SetSensorInteractiveMarker > {
  static const char* value()
  {
    return "8512eb1fbd109250c8778605b27356c3";
  }

  static const char* value(const ::atom_msgs::SetSensorInteractiveMarker&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::SetSensorInteractiveMarker > {
  static const char* value()
  {
    return "atom_msgs/SetSensorInteractiveMarker";
  }

  static const char* value(const ::atom_msgs::SetSensorInteractiveMarker&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::SetSensorInteractiveMarkerRequest> should match
// service_traits::MD5Sum< ::atom_msgs::SetSensorInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::SetSensorInteractiveMarkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetSensorInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SetSensorInteractiveMarkerRequest> should match
// service_traits::DataType< ::atom_msgs::SetSensorInteractiveMarker >
template<>
struct DataType< ::atom_msgs::SetSensorInteractiveMarkerRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetSensorInteractiveMarkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::SetSensorInteractiveMarkerResponse> should match
// service_traits::MD5Sum< ::atom_msgs::SetSensorInteractiveMarker >
template<>
struct MD5Sum< ::atom_msgs::SetSensorInteractiveMarkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::SetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetSensorInteractiveMarkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::SetSensorInteractiveMarkerResponse> should match
// service_traits::DataType< ::atom_msgs::SetSensorInteractiveMarker >
template<>
struct DataType< ::atom_msgs::SetSensorInteractiveMarkerResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::SetSensorInteractiveMarker >::value();
  }
  static const char* value(const ::atom_msgs::SetSensorInteractiveMarkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_SETSENSORINTERACTIVEMARKER_H
