// Generated by gencpp from file atom_msgs/ToggleAutomaticDataCollector.msg
// DO NOT EDIT!


#ifndef ATOM_MSGS_MESSAGE_TOGGLEAUTOMATICDATACOLLECTOR_H
#define ATOM_MSGS_MESSAGE_TOGGLEAUTOMATICDATACOLLECTOR_H

#include <ros/service_traits.h>


#include <atom_msgs/ToggleAutomaticDataCollectorRequest.h>
#include <atom_msgs/ToggleAutomaticDataCollectorResponse.h>


namespace atom_msgs
{

struct ToggleAutomaticDataCollector
{

typedef ToggleAutomaticDataCollectorRequest Request;
typedef ToggleAutomaticDataCollectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleAutomaticDataCollector
} // namespace atom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atom_msgs::ToggleAutomaticDataCollector > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollector&) { return value(); }
};

template<>
struct DataType< ::atom_msgs::ToggleAutomaticDataCollector > {
  static const char* value()
  {
    return "atom_msgs/ToggleAutomaticDataCollector";
  }

  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollector&) { return value(); }
};


// service_traits::MD5Sum< ::atom_msgs::ToggleAutomaticDataCollectorRequest> should match
// service_traits::MD5Sum< ::atom_msgs::ToggleAutomaticDataCollector >
template<>
struct MD5Sum< ::atom_msgs::ToggleAutomaticDataCollectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::ToggleAutomaticDataCollector >::value();
  }
  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::ToggleAutomaticDataCollectorRequest> should match
// service_traits::DataType< ::atom_msgs::ToggleAutomaticDataCollector >
template<>
struct DataType< ::atom_msgs::ToggleAutomaticDataCollectorRequest>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::ToggleAutomaticDataCollector >::value();
  }
  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atom_msgs::ToggleAutomaticDataCollectorResponse> should match
// service_traits::MD5Sum< ::atom_msgs::ToggleAutomaticDataCollector >
template<>
struct MD5Sum< ::atom_msgs::ToggleAutomaticDataCollectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atom_msgs::ToggleAutomaticDataCollector >::value();
  }
  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atom_msgs::ToggleAutomaticDataCollectorResponse> should match
// service_traits::DataType< ::atom_msgs::ToggleAutomaticDataCollector >
template<>
struct DataType< ::atom_msgs::ToggleAutomaticDataCollectorResponse>
{
  static const char* value()
  {
    return DataType< ::atom_msgs::ToggleAutomaticDataCollector >::value();
  }
  static const char* value(const ::atom_msgs::ToggleAutomaticDataCollectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATOM_MSGS_MESSAGE_TOGGLEAUTOMATICDATACOLLECTOR_H
