# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from atom_msgs/RGBLabels.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import atom_msgs.msg

class RGBLabels(genpy.Message):
  _md5sum = "490746e211ca178da64659e6df5e160d"
  _type = "atom_msgs/RGBLabels"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string pattern_name
bool detected
Detection2D[] idxs

================================================================================
MSG: atom_msgs/Detection2D
float32 x
float32 y
uint32 id

"""
  __slots__ = ['pattern_name','detected','idxs']
  _slot_types = ['string','bool','atom_msgs/Detection2D[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pattern_name,detected,idxs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RGBLabels, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pattern_name is None:
        self.pattern_name = ''
      if self.detected is None:
        self.detected = False
      if self.idxs is None:
        self.idxs = []
    else:
      self.pattern_name = ''
      self.detected = False
      self.idxs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.pattern_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      length = len(self.idxs)
      buff.write(_struct_I.pack(length))
      for val1 in self.idxs:
        _x = val1
        buff.write(_get_struct_2fI().pack(_x.x, _x.y, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.idxs is None:
        self.idxs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pattern_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pattern_name = str[start:end]
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.idxs = []
      for i in range(0, length):
        val1 = atom_msgs.msg.Detection2D()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.id,) = _get_struct_2fI().unpack(str[start:end])
        self.idxs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.pattern_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      length = len(self.idxs)
      buff.write(_struct_I.pack(length))
      for val1 in self.idxs:
        _x = val1
        buff.write(_get_struct_2fI().pack(_x.x, _x.y, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.idxs is None:
        self.idxs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pattern_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pattern_name = str[start:end]
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.idxs = []
      for i in range(0, length):
        val1 = atom_msgs.msg.Detection2D()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.id,) = _get_struct_2fI().unpack(str[start:end])
        self.idxs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fI = None
def _get_struct_2fI():
    global _struct_2fI
    if _struct_2fI is None:
        _struct_2fI = struct.Struct("<2fI")
    return _struct_2fI
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
