(cl:defpackage atom_msgs-msg
  (:use )
  (:export
   "<DEPTHIMAGEWITHDEPTHLABELS>"
   "DEPTHIMAGEWITHDEPTHLABELS"
   "<DEPTHLABELS>"
   "DEPTHLABELS"
   "<DETECTION2D>"
   "DETECTION2D"
   "<IMAGEWITHRGBLABELS>"
   "IMAGEWITHRGBLABELS"
   "<LIDAR3DLABELS>"
   "LIDAR3DLABELS"
   "<POINTCLOUDWITHLIDAR3DLABELS>"
   "POINTCLOUDWITHLIDAR3DLABELS"
   "<RGBLABELS>"
   "RGBLABELS"
  ))

