axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.3

axis_angular: 3  # Left thumb stick horizontal
scale_angular: 3.5

enable_button: 5  # Left trigger button
enable_turbo_button: 4  # Right trigger button
